apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-txerjzfb
  janus-idp.io/tekton: go-txerjzfb
  backstage.io/kubernetes-id: go-txerjzfb
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-txerjzfb
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
